name: Continuous Integration
on: [push]
jobs:
  router:
    name: Besoin d'un job ?
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ubuntu-latest]
        php-versions: ['7.4']
    steps:
      - name: step 1
        run: php --version
      - name: step 2 multi script
        run: |
          node -v
          yarn -v
          npm -v