name: Continuous Integration
on: [push]
jobs:
  router:
    name: Besoin d'un job ?
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ubuntu-latest]
        php-versions: ['7.4']
